### ISSUE TITLE
best redux example ever

### ISSUE THREAD

**Issue by terrysahaidak** [andrewngu/sound-redux#1]
hey, @andrewngu, I really like work you've done with soundredux. it looks amazing!
do you have a plans to add some authentication and error handling to your app? 
be cause if you'll add it, this is will be the best redux example ever!

**Comment by andrewngu** [comment]
Thanks for the kind words Terry, I'm planning on adding full Soundcloud integration so that you'll be able to favorite songs, create playlists and play all your saved soundcloud playlists. Hopefully by this weekend or next :)

**Comment by terrysahaidak** [comment]
Thank you for your work. I'll be waiting for that :)
This app is a kind of inspiration!
