### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to load because no supported source was found.

### ISSUE THREAD

**Issue by cichy** [andrewngu/sound-redux#127]
It worked fine yesterday today I'm getting this don't know why.
Chrome version: 61.0.3163.100
MacBook Pro (Retina, 13-inch, Late 2013)
2,4 GHz Intel Core i5
8 GB 1600 MHz DDR3
os: high sierra

This may help
https://developers.google.com/web/updates/2016/03/play-returns-promise?hl=en

**Comment by andrewngu** [comment]
I believe playback is failing because the api key that is provided with the repo has reached its playback limit. I should probably handle this error more gracefully. If you check the network tab while trying to play a song you might see a `429 too many requests` error.
