### ISSUE TITLE
Doing a clone in Elm

### ISSUE THREAD

**Issue by gabrielperales** [andrewngu/sound-redux#130]
Hi, I just wanted to tell you that I'm coding a clone of your app in Elm. I'm horrible designing stuff, so I took your design as a _base_. I hope you don't mind it... 

I have to add a reference to this repo, and I'll do it when the project is more complete. If you want to check it out, [here](https://github.com/gabrielperales/elm-soundcloud-player) is the repo.

Thank you.

**Comment by andrewngu** [comment]
No worries, sounds like a cool project.
