### ISSUE TITLE
Music List is not loading on Production

### ISSUE THREAD

**Issue by chinmaydalvi** [andrewngu/sound-redux#132]
Music list is not loading on live website `https://soundredux.io/#/`. Server is sending an error 404 not found. Attaching the screenshot of console. Not sure if is this Client_key issue as mentioned earlier #129 

![no_music](https://user-images.githubusercontent.com/14978241/34321689-6e8d4eb2-e83b-11e7-80a4-fb73c3ad0fdf.png)

**Comment by gEndelf** [comment]
It seems API was updated

**Comment by anthonybrown** [comment]
is anyone working on resolving this?

**Comment by Craig-Cheng** [comment]
i have the same problem
