### ISSUE TITLE
Ability to like tracks

### ISSUE THREAD

**Issue by ZogStriP** [andrewngu/sound-redux#14]
I listen to music all day and I always need new music. I discovered this project a week ago and I :heart: so much! Thanks a lot for it :+1:

Currently, the only feature I'm missing is the ability to like a track so that I can create a playlist of tracks I enjoy.

**Comment by andrewngu** [comment]
Glad you're enjoying it. :)

Authentication with SoundCloud is on its way. Hopefully by the end of this week.

**Comment by ZogStriP** [comment]
Awesome :+1:

**Comment by ZogStriP** [comment]
You rock :metal:

**Comment by andrewngu** [comment]
lol, thanks. lemme know if you notifce any bugs :)
