### ISSUE TITLE
Please upload the module "../components/SongCards".

### ISSUE THREAD

**Issue by WenXuanYuan** [andrewngu/sound-redux#16]
I am a fresher to redux, and I see this example in github, but when try to run my browser says 'Uncaught Error: Cannot find module "../components/SongCards"', I also can`t find SongCards component in master branch.

**Comment by WenXuanYuan** [comment]
The model was import in components/Me.js && songs.js

**Comment by andrewngu** [comment]
Can you try pulling origin master? Sorry about that, I renamed some components and switched up the file names.

**Comment by WenXuanYuan** [comment]
I see, Would you give me the final version which can run of this project. I am a freshman and find this example is more cool.

**Comment by WenXuanYuan** [comment]
Thank you , i have download the model successfully.

**Comment by andrewngu** [comment]
:+1:
