### ISSUE TITLE
Not an issue, but...

### ISSUE THREAD

**Issue by zwhitchcox** [andrewngu/sound-redux#19]
Just wanted to say, beautiful app man. Really nicely done.

And you're just learning this? That's incredible. Very humbling to me.

**Comment by andrewngu** [comment]
Thanks for the kind words :smile: This app is more of a testament of how much you can get done when you have stellar tools.

This was the first project where I've used Redux and ES6, so that experience was new to me, but they're both awesome tools that made things much easier and a lot more enjoyable. Don't be so impressed, it's mostly CSS :wink:

**Comment by fraserxu** [comment]
@zwhitchcox Agree! This is really nice written code! Learned a lot! 

Thanks @andrewngu !

**Comment by andrewngu** [comment]
Happy to hear you're learning something from it!

**Comment by nxnfufunezn** [comment]
use it everyday..good work mate.. :+1:
waiting for desktop app..

**Comment by terrysahaidak** [comment]
Just want to ask: 
Can i use your awesome player component in my own open source project?

**Comment by andrewngu** [comment]
@terrysahaidak Go for it. This project uses the GNU GPL so feel free to use it in any open source project. :+1:

**Comment by terrysahaidak** [comment]
thank you for your work!

**Comment by synthomat** [comment]
@andrewngu great work and a good source of inspiration :)

Question: why did you create "Containers" which aparently just wrapp connect() around other components? Just to decouple the "dumb components" from the redux-framework?

Thanks!

**Comment by andrewngu** [comment]
Yeah, I created those containers to avoid having to write my mapStateToProps functions twice, since both the mobile components and their non mobile counterparts require the same props. There probably is a cleaner way to do it, however.

**Comment by andrewngu** [comment]
Also, using containers can prevent unnecessary re-renders and makes your code a bit more organized. Consider this render function
```
render() {
        return (
            <div>
                <NavContainer />
                <PlayerContainer />
                <ModalContainer />
            </div>
        );
}
```
compared to this
```
render() {
    const {authed, authedPlaylists, dispatch, modal, navigator, player, playingSongId, playlists, songs, users} = this.props;

    return (
        <div>
            <Nav
                authed={authed}
                authedPlaylists={authedPlaylists}
                dispatch={dispatch}
                navigator={navigator}
                songs={songs} />
            <Modal dispatch={dispatch} modal={modal} />
            <Player
                dispatch={dispatch}
                player={player}
                playingSongId={playingSongId}
                playlists={playlists}
                songs={songs}
                users={users} />
        </div>
    );
}
```
Which looks cleaner and easier to reason about? Also, keep in mind that any update to any of those props in the second render function will cause a re-render for ALL of the components. That could be solved by `PureRenderMixin` but still...

**Comment by terrysahaidak** [comment]
@andrewngu what about something like [this](https://gist.github.com/acdlite/453f227f5e5cbbf105f8)?

**Comment by andrewngu** [comment]
Yep, that's a good idea. Wrapping your components with higher order component with PureRenderMixin would definitely improve performance. Also using Immutable.js would make it fly.

**Comment by terrysahaidak** [comment]
@andrewngu also you should look on [this](http://joshbroton.com/hooking-up-to-the-window-onscroll-event-without-killing-your-performance/) to improve better performance of your skickify higher-order component, because it's really laggy (in my case).

**Comment by andrewngu** [comment]
Thanks @terrysahaidak I've been meaning to fix that. Not sure if the lagginess is because of the actual scroll event firing too often or if it's related to the dom element getting the `position: fixed` setting...

**Comment by gusaiani** [comment]
Hi Andrew,

I second everybody here in thanking you for this app...it’s beautiful, extremely instructive, very nice work.

I also have a question:
in `actions/playlists.js`, you explicitly import `isomorphic-fetch`.
in `actions/authed.js` and other actions, you don’t import `isomorphic-fetch`.
That got my head scratching: how can all the fetches run in their files without imports? Are they injected? Where are they coming from?

Consequently, could one delete the import from `actions/playlists.js` without breaking the app?

Thanks again!

**Comment by terrysahaidak** [comment]
@gusaiani because there are already imported some polyfils in [main.js](https://github.com/andrewngu/sound-redux/blob/master/scripts/main.js#L1).

**Comment by andrewngu** [comment]
Hey @gusaiani Thanks for the kind words.
If you look at the `isomorphic-fetch` repo, when you import the library, it overwrites `global.fetch` if it's undefined.

https://github.com/matthew-andrews/isomorphic-fetch/blob/master/fetch-npm-node.js

You're absolutely right, the import from `actions/playlists.js` can be removed.

**Comment by gusaiani** [comment]
@terrysahaidak @andrewngu 
Thanks :)

**Comment by gusaiani** [comment]
Hi @andrewngu, 
I started running the application locally again, after a few days.
When I login to Soundcloud and/or hit 'Connect', the SC popup never closes, and my console shows:

![image](https://cloud.githubusercontent.com/assets/380816/11380673/a77af24c-92de-11e5-95a5-d0cb86beb6a4.png)

Has that happened to you? Any idea what it might be?
Many thanks!

**Comment by zzz6519003** [comment]
just wanna say i just `brew isntall go`

and i get myself fucked up with go path XD....


can you please tell me what to do next, specificcly?
 :beer:

**Comment by napcae** [comment]
@zzz6519003 what do you want to achieve?

**Comment by zzz6519003** [comment]
setup the enviroment XD
