### ISSUE TITLE
Vendor prefixes

### ISSUE THREAD

**Issue by vkzawa** [andrewngu/sound-redux#2]
Sweet project you have here. I really like the UI.

I noticed your layout is broken in Safari.
You can get a nice bump in browser support by including autoprefixer in your CSS output. It does all the work for you. :grinning: 

Here's a link to autoprefixer for webpack:
https://github.com/passy/autoprefixer-loader

**Comment by andrewngu** [comment]
Thanks for feedback @vkzawa , I've included autoprefixer as a loader in webpack. Please let me know if that resolves your issue. Also, I'm curious which version of safari you are using. I'm on 9 and don't see any layout issues.
