### ISSUE TITLE
Better way to show currently playing song

### ISSUE THREAD

**Issue by ZogStriP** [andrewngu/sound-redux#23]
While the current UI is very nice I find it has 1 drawback: being able to **quickly** identify which track is currently playing...

_Can you find which track is currently playing in less than 5 seconds?_
![which one is currently playing](https://cloud.githubusercontent.com/assets/362783/11041394/e059f974-8711-11e5-8f8d-2572493b6636.png)

Maybe changing the background of the track to a green-ish color might help?

**Comment by andrewngu** [comment]
Good point, been thinking about this for awhile. I tried the green-ish background color, but wasn't happy with the way it looked. I was also thinking some sort of visualization might be nice.

**Comment by ZogStriP** [comment]
Mind explaining what you mean by "some sort of visualization"?

**Comment by andrewngu** [comment]
http://jeffpeterson.github.io/music/ 
something like this or with waveform bars.

**Comment by ZogStriP** [comment]
Ok. I personally have no use for that but if you feel like adding it, no biggie ;)

**Comment by andrewngu** [comment]
I think if the card had moving bars over it's artwork, while it was being played, it might be easier to spot it. I'll try it out and we can see if that solves the problem :wink:

**Comment by ZogStriP** [comment]
Oh, I see what you mean. Yeah I think that could work :+1:
