### ISSUE TITLE
Automatically load next tracks

### ISSUE THREAD

**Issue by ZogStriP** [andrewngu/sound-redux#24]
It would be awesome for the player to automatically load the next page of tracks when it's playing one of the latest currently loaded tracks. Currently, it either stops, or loops back to the first loaded track.

_Note: this doesn't (and shouldn't) have to work in random mode._

**Comment by andrewngu** [comment]
Really good idea!

**Comment by danep93** [comment]
Is anyone working on this? I'd like to this up

**Comment by andrewngu** [comment]
@danep93 feel free to take a shot at it 👍
