### ISSUE TITLE
Starting Go server

### ISSUE THREAD

**Issue by andrewngu** [andrewngu/sound-redux#34]
@gusaiani Creating a new issue here so we can avoid spamming a few people. To answer your question about auth, it's actually being handled using a go server (which is in the same repo in the `server` folder). To get auth running locally you need to compile the go app and run it.

If the `sound-redux` folder is in your `$GOPATH` you can just do this
`$ cd server`
`$ go get .`
`$ go install .`
`$ server`

**Comment by gusaiani** [comment]
Thank you once again, Andrew. :)

**Comment by andrewngu** [comment]
no problem, let me know if you have any other issues :+1:
