### ISSUE TITLE
Error on npm install command

### ISSUE THREAD

**Issue by DanPhyxius** [andrewngu/sound-redux#57]
Hi guys!

congrats, nice job with this repository! 
I'm studying Redux/React and i'm trying to install your project locally, but i get an error on
npm install command.

<img width="716" alt="schermata 2016-06-01 alle 12 40 40" src="https://cloud.githubusercontent.com/assets/4693301/15707082/00d974e6-27f7-11e6-87a0-15eb55081034.png">

It seems is fault of eslint version. Can you help me?

Thanks to all,
Dan

**Comment by andrewngu** [comment]
Hey @DanPhyxius, I just updated the packages. Try removing your `node_modules` folder and running `npm install` again and let me know if you run into any issues.
