### ISSUE TITLE
API key exposed, reverse proxy needed?

### ISSUE THREAD

**Issue by BlueAccords** [andrewngu/sound-redux#64]
Are you planning on adding a reverse proxy of some sort to forward your soundcloud api requests to? 

Or is it a non-issue since this project was meant to be a non-trivial educational project at learning react/redux?

I'm asking since i'm trying to do a similar project but I'm getting caught up on trying to not expose the api key myself.

**Comment by andrewngu** [comment]
Since the project is mostly educational, I don't see any issues exposing API key. Especially since it doesn't nearly approach the rate-limit.
