### ISSUE TITLE
Query regarding syntax for creating store using redux-thunk

### ISSUE THREAD

**Issue by jinxac** [andrewngu/sound-redux#69]
I was trying to understand the code of `sound-redux` app. First of all I must amazing work and very clean code.

I was able to get most of the code but I had a doubt regarding the way the store was created.

From the code I can see the following:-

```
import { createStore, applyMiddleware } from 'redux';
import thunk from 'redux-thunk';
import rootReducer from '../reducers/index';

const createStoreWithMiddleware = applyMiddleware(thunk)(createStore);  

export default function configureStore(initialState) {
  const store = createStore(rootReducer, applyMiddleware(thunk));
  return store;
}
```

But after going through redux-thunk documentation I tried implementing it as mentioned in the way it  was in the documentation. So I tried following code which seems to work fine. **So I was trying to understand what was the logic behind writing the code as above**. Can you please help me?

```
import { createStore, applyMiddleware } from 'redux';
import thunk from 'redux-thunk';
import rootReducer from '../reducers/index';

export default function configureStore(initialState) {
  const store=createStore(rootReducer,applyMiddleware(thunk))
  return store
}
```

**Comment by andrewngu** [comment]
To be perfectly honest, I think the redux api may have changed a bit since I started this project and may have been following an older example. A similar issue was discussed in the redux repo:

https://github.com/reactjs/redux/issues/1236
