### ISSUE TITLE
Play/Pause song by clicking in the logo

### ISSUE THREAD

**Issue by alfonsoperez** [andrewngu/sound-redux#7]
Hi!, 

Really cool app, been using it for a couple of days while working :-). 
It would be nice to be able to play/pause a use by clicking in it's logo. Currently you can play it, but to pause you have to go to the player, I can submit a PR if I have some time later in the week if you find this appropriate.

**Comment by andrewngu** [comment]
Thanks, glad you're liking it. Yah, I've been meaning to fix that, but just been putting it off. Feel free to take a shot at it :+1:
