### ISSUE TITLE
Error: Cannot resolve module 'react/lib/ReactMount'

### ISSUE THREAD

**Issue by vsc-github** [andrewngu/sound-redux#79]
Such a nice open source project. 
I just cloned the repo. Did an ```npm install``` , then ```npm start```.
When I go to ```http://localhost:8080``` , I get this error in browser console

> Uncaught Error: Cannot find module "react/lib/ReactMount"

and this error in the command line console for all the js files:
> Module not found: Error: Cannot resolve module 'react/lib/ReactMount' in <filename>

I tried looking over stackoverflow and google, people have suggested changing the version of react dependencies. But it didn't help. Is there any other solution/workaround to this?

**Comment by iHelos** [comment]
Hey, just solved the same problem for me:
1) set the last version of "react-hot-loader" in package.json:
`"react-hot-loader": "^3.0.0-beta.6",`
2) in webpack.config change "react-hot" with "react-hot-loader/webpack", so you'll get something like this:
`{ test: /\.js$/, loaders: ['react-hot-loader/webpack', 'babel?' + JSON.stringify({presets: ['react', 'es2015', 'stage-0']})], exclude: /node_modules/ },`
3) `npm run start`

**Comment by AmitMundra54** [comment]
thanks, buddy it worked for me
