### ISSUE TITLE
add routing

### ISSUE THREAD

**Issue by findjashua** [andrewngu/sound-redux#9]
add some simple routing, i'm thinking something like `genre/songId`

if you think react router is too heavy, you could use something light like page.js or even just regex on `window.location.pathname`

**Comment by andrewngu** [comment]
http://soundredux.io/#/songs/203112765 :smile:

**Comment by terrysahaidak** [comment]
what about search params? for example soundredux.io/#/songs/?q=Affecting%20Dissent should display songs by Affecting Dissent

**Comment by andrewngu** [comment]
good point, in progress

**Comment by andrewngu** [comment]
http://soundredux.io/#/songs?q=Affecting%20Dissent :wink:
